# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: windows-latest

resources:
  repositories:
  - repository: TestAutomation
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-devops
    trigger:
      batch: true
      branches:
        include:
        - main

stages:
- stage: UnitTests
  condition: eq(variables.isPR, true)
  displayName: "Unit Test"
  jobs:
  - job:
    steps:
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/DotNet/DotNet.Test/DotNet.Test.csproj'

- stage: Deploy
  condition: eq(variables.isMain, true)
  displayName: "Deploy Azure Function"
  jobs:
  - job:
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

- stage: FunctionalTests
  condition: eq(variables.isMain, true)
  displayName: "Run Functional Test Automation"
  jobs:
  - job:
    steps:
      - script: echo Hello Stage Functional Tests!
