# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: EZWM
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-devops
    trigger:
      batch: true
      branches:
        include:
        - main

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
