# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: windows-latest

resources:
  repositories:
  - repository: TestAutomation
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-devops
    trigger:
      batch: true
      branches:
        include:
        - main

stages:
- stage: UnitTests
  condition: eq(variables.isPR, true)
  displayName: "Unit Test"
  jobs:
  - job: UnitTests
    steps:
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.Test.csproj'

- stage: Deploy
  condition: eq(variables.isMain, true)
  displayName: "Deploy Azure Function"
  jobs:
  - job: Deploy
    displayName: 'Deploy Azure Function'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'AzFun_SC'
        appType: 'functionApp'
        appName: 'adsuho-f2'
        package: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        deploymentMethod: 'auto'
  
- stage: FunctionalTests
  condition: and(succeeded('Deploy'), eq(variables.isMain, true))
  displayName: 'Run Functional Test Automation'
  jobs:
  - job: FunctionalTests
    steps:
      - script: echo Hello Stage Functional Tests!
