# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: TestAutomation
    type: github
    endpoint: adriansuhov
    name: adriansuhov/azure-devops
    trigger:
      batch: true
      branches:
        include:
        - main

stages:
- stage: UnitTests
  condition: and(succeeded(), eq(variables.isPR, true))
  displayName: "Unit Test"
  jobs:
  - job:
    steps:
      - script: echo Hello Stage Unit Tests!

- stage: Deploy
  condition: and(succeeded(), eq(variables.isMain, true))
  displayName: "Deploy Azure Function"
  jobs:
  - job:
    steps:
      - script: echo Hello Stage Deploy!

- stage: FunctionalTests
  condition: and(succeeded(), eq(variables.isMain, true))
  displayName: "Run Functional Test Automation"
  jobs:
  - job:
    steps:
      - script: echo Hello Stage Functional Tests!
